name: qawolf
on:
  push:
    branches: "*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 50
      - name: qawolf test
        uses: docker://qawolf/qawolf:v0.7.11
        with:
          args: "qawolf test"
        env:
          QAW_DOM_PATH: /github/workspace/artifacts
          QAW_LOG_PATH: /github/workspace/artifacts
          QAW_VIDEO_PATH: /github/workspace/artifacts
          URL: http://countly
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: qawolf
          path: "./artifacts"
    services:
      countly:
        image: countly/countly-server:latest
